### PR TITLE
Add leaflet map

### PR DESCRIPTION
**Pull request by Williangalvani**
map

### CODE REVIEW

**Comment by stephendade** [comment]
Very nice!

Unfortunately got some layout issues on Firefox 77 / Ubuntu 18.04. It might be due to my smallish screen resolution (1366x768):

Screenshot from 2020-06-30 21-46-17
Screenshot from 2020-06-30 21-46-28

**Comment by Williangalvani** [comment]
I'll summon @biakp to help with the css. I can do basic stuff but it is incredibly frustrating, haha.
Expect updates soon!

**Comment by Williangalvani** [comment]
@stephendade do you mind testing now? I did some tweaks. I'm also limiting the center to +-60 degrees now.

@biakp has a new design but I think it might be best to keep it on it's own pr

**Comment by stephendade** [comment]
I've done a quick test. Previous layout issues are fixed. Two other issues found:
- Zoom resets whenever I click a new position on the map.
- Longitude values 0 -> 360 rather than the required -180 -> +180.

**Comment by Williangalvani** [comment]
Oh damn, leaflet allows you to scroll indefinitely and just increases the longitute forever...

Updated!

**Comment by stephendade** [comment]
Thanks! merging

**Pull request merged**
