### PR TITLE
Add new terrain file format

### PR DESCRIPTION
**Pull request by stephendade**
Allows user to select version of terrain, where V2 is used in ArduPilot 4.1+

Also includes new generation scripts.

### CODE REVIEW

**Comment by tridge** [comment]
> Allows user to select version of terrain, where V2 is used in ArduPilot 4.1+

I don't see why we should change the version number in the data format. The existing margin check should be sufficient?

**Comment by tridge** [comment]
the TERRAIN_MARGIN param has been merged now

**Comment by Hwurzburg** [comment]
I think we should just go to V2 and be done with it....users with old files that cant be updated can use the _MARGIN....most will just redownload and go...dont really see a need to generate old sets any more

**Comment by stephendade** [comment]
Due to git shenanigans, I'm closing this and using #4 instead.

**Pull request closed without merging**
